# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Minseong Gil
title: Integrated M.S./Ph.D. Student in Computer Architecture and System Software
location: Seoul, Korea
email: ms7859@korea.ac.kr
website: https://github.com/Minseong-Gil

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://github.com/comsys-lab
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I am Minseong Gil, a Ph.D. student at Korea University. I conduct research in GPU architecture at the Computer Architecture and System Software Lab (ComSys), advised by Professor Younho Oh.

  My research focuses on GPU microarchitecture and high-performance GPU computing, particularly in hardware design for computational efficiency and software techniques for optimized GPU execution. I am interested in CUDA programming, GPU execution efficiency, and enhancing GPU microarchitecture to improve AI workload performance.

  For more details about my research and publications, please check out the rest of my website.

content:
  # - title: Research # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: GPU Software Techniques and Microarchitecture
  #       description: |
  #         My research focuses on GPU software techniques and microarchitecture improvements, aiming to enhance both execution efficiency and computational capabilities. 
  #         I explore thread allocation strategies for multi-tenant GPU inference workloads, optimizing resource management to improve performance and scalability. 
  #         Also, I work on GPU microarchitecture enhancements, designing novel techniques that support advanced numeric formats. 
  #         My work contributes to more efficient and scalable GPU computing for high-performance and AI workloads.

  #     - layout: top-middle
  #       title: CXL Memory System
  #       description: |
  #         To be added.

  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IEEE TC
        # link: https://dl.acm.org/doi/abs/10.1145/3735452.3735529
        # link_text: Read More
        sub_title: Top journal in computer architecture
        caption: 2026
        description: >
            **Bauhaus: Restructuring Vector Database for LLM Retrieval on CXL-Based Tiered Memory**<br>
            Kyungbin Kim, Sungsu Ahn, Wonjung Jeong, Jongmin Kim, Sangun Choi, <b><u>Minseong Gil</u></b>, Minseong Kim, Dongha Jeong, Yunjay Hong, Haekang Jung, and Yunho Oh
      
      - layout: left
        title: IEEE CAL
        link: https://ieeexplore.ieee.org/document/11038933
        link_text: Read More
        sub_title: Major journal in computer architecture
        caption: 2025
        description: >
            **MOST: Memory Oversubscription-aware Scheduling for Tensor Migration on GPU Unified Storage**<br>
            Junsu Kim, Jaebeom Jeon, Jaeyong Park, Sangun Choi, <b><u>Minseong Gil</u></b>, Seokin Hong, Gunjae Koo, Myung Kuk Yoon, and Yunho Oh
      
      - layout: left
        title: LCTES 2025
        link: https://dl.acm.org/doi/abs/10.1145/3735452.3735529
        link_text: Read More
        sub_title: Major conference in embedded systems
        caption: 2025
        description: >
            **SSFFT: Energy-Efficient Selective Scaling for Fast Fourier Transform in Embedded GPUs**<br>
            Dongwon Yang, Jaebeom Jeon, <b><u>Minseong Gil</u></b>, Junsu Kim, Seondeok Kim, Gunjae Koo, Myung Kuk Yoon, and Yunho Oh
      
      - layout: left
        title: LCTES 2025
        link: https://dl.acm.org/doi/abs/10.1145/3735452.3735537
        link_text: Read More
        sub_title: Major conference in embedded systems
        caption: 2025
        description: >
            **Kubism: Disassembling and Reassembling K-Means Clustering for Mobile Heterogeneous Platforms**<br>
            Seondeok Kim, Sangun Choi, Jaebeom Jeon, Junsu Kim, <b><u>Minseong Gil</u></b>, Jaehyeok Ryu, and Yunho Oh
      
      - layout: left
        title: ISCA 2025
        link: https://dl.acm.org/doi/10.1145/3695053.3731100
        link_text: Read More
        sub_title: Top-tier Conference
        caption: 2025
        description: >
            **Avant-Garde: Empowering GPUs with Scaled Numeric Formats**<br>
            <b><u>Minseong Gil</u></b>, Dongho Ha, Simla Burcu Harma, Myung Kuk Yoon, Babak Falsafi, Won Woo Ro, and Yunho Oh
      
      - layout: left
        title: IEEE ESL
        link: https://ieeexplore.ieee.org/document/10753458
        link_text: Read More
        sub_title: Major journal in embedded systems
        caption: 2024
        description: >
            **TLP Balancer: Predictive Thread Allocation for Multi-Tenant Inference in Embedded GPUs**<br>
            <b><u>Minseong Gil</u></b>, Jaebeom Jeon, Junsu Kim, Sangun Choi, Gunjae Koo, Myung Kuk Yoon, and Yunho Oh
      
      - layout: left
        title: ICPP 2024
        link: https://dl.acm.org/doi/10.1145/3673038.3673045
        link_text: Read More
        sub_title: Major conference in computer architecture
        caption: 2024
        description: >
            **VitBit: Enhancing Embedded GPU Performance for AI Workloads through Register Operand Packing**<br>
            Jaebeom Jeon, <b><u>Minseong Gil</u></b>, Junsu Kim, Jaeyong Park, Gunjae Koo, Myung Kuk Yoon, and Yunho Oh

  # - title: Publications
  #   layout: list
  #   content:
  #   - layout: top
  #     description: >
  #       <b>IEEE CAL (Major journal in computer architecture)</b><br>
  #       MOST: Memory Oversubscription-aware Scheduling for Tensor Migration on GPU Unified Storage<br>
  #       Junsu Kim, Jaebeom Jeon, Jaeyong Park, Sangun Choi, <b><u>Minseong Gil</u></b>, Seokin Hong, Gunjae Koo, Myung Kuk Yoon, and Yunho Oh
  #       <a href="https://doi.org/10.1109/MCAL.2025.1234567" target="_blank">Read More</a>

  #   - layout: top
  #     description: >
  #       <b>LCTES 2025 (Major conference in embedded systems)</b><br>
  #       SSFFT: Energy-Efficient Selective Scaling for Fast Fourier Transform in Embedded GPUs<br>
  #       Dongwon Yang, Jaebeom Jeon, <b><u>Minseong Gil</u></b>, Junsu Kim, Seondeok Kim, Gunjae Koo, Myung Kuk Yoon, Yunho Oh<br>
  #       <a href="https://doi.org/10.1145/3735452.3735529" target="_blank">Read More</a>

  #   - layout: top
  #     description: >
  #       <b>LCTES 2025 (Major conference in embedded systems)</b><br>
  #       Kubism: Disassembling and Reassembling K-Means Clustering for Mobile Heterogeneous Platforms<br>
  #       Seondeok Kim, Sangun Choi, Jaebeom Jeon, Junsu Kim, <b><u>Minseong Gil</u></b>, Jaehyeok Ryu, Yunho Oh<br>
  #       <a href="https://doi.org/10.1145/3735452.3735537" target="_blank">Read More</a>

  #   - layout: top
  #     description: >
  #       <b>ISCA 2025 (Top-tier Conference)</b><br>
  #       Avant-Garde: Empowering GPUs with Scaled Numeric Formats<br>
  #       <b><u>Minseong Gil</u></b>, Dongho Ha, Simla Burcu Harma, Myung Kuk Yoon, Babak Falsafi, Won Woo Ro, Yunho Oh<br>
  #       <a href="https://doi.org/10.1145/3695053.3731100" target="_blank">Read More</a>

  #   - layout: top
  #     description: >
  #       <b>IEEE ESL (Major journal in embedded systems)</b><br>
  #       TLP Balancer: Predictive Thread Allocation for Multi-Tenant Inference in Embedded GPUs<br>
  #       <b><u>Minseong Gil</u></b>, Jaebeom Jeon, Junsu Kim, Sangun Choi, Gunjae Koo, Myung Kuk Yoon, Yunho Oh<br>
  #       <a href="https://doi.org/10.1109/LES.2024.10753458" target="_blank">Read More</a>

  #   - layout: top
  #     description: >
  #       <b>ICPP 2024 (Major conference in computer architecture)</b><br>
  #       VitBit: Enhancing Embedded GPU Performance for AI Workloads through Register Operand Packing<br>
  #       Jaebeom Jeon, <b><u>Minseong Gil</u></b>, Junsu Kim, Jaeyong Park, Gunjae Koo, Myung Kuk Yoon, Yunho Oh<br>
  #       <a href="https://doi.org/10.1145/3673038.3673045" target="_blank">Read More</a>



  - title: Education
    layout: text
    content: |
        - B.S. in Electronic Engineering, Ajou University, 2023
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
